@startjson
{
  "global": {
    "fabricVersion": "2.4.3",
    "tls": true
  },
  "orgs": [
    {
      "organization": {
        "name": "Orderer",
        "domain": "orderer.project.it"
      },
      "orderers": {
          "groupName": "group1",
          "type": "raft",
          "instances": 3
      }
    },
    {
      "organization": {
        "name": "Landlord_num",
        "domain": "landlord_num.project.it"
      },
      "peer": {
        "instances": 1,
        "anchorPeerInstances": 1,
        "db": "CouchDb"
      }
    },
    {
      "organization": {
        "name": "Tenant_num",
        "domain": "tenant_num.project.it"
      },
      "peer": {
        "instances": 1,
        "anchorPeerInstances": 1,
        "db": "CouchDb"
      }
    },
    {
      "organization": {
        "name": "Guest_num",
        "domain": "guest_num.project.it"
      },
      "peer": {
        "instances": 1,
        "anchorPeerInstances": 1,
        "db": "CouchDb"
      }
    },
    {
      "organization": {
        "name": "Sensors_num",
        "domain": "sensors_num.project.it"
      },
      "peer": {
        "instances": 1,
        "anchorPeerInstances": 1,
        "db": "CouchDb"
      }
    }
  ],
  "channels":
    {
      "name": "home_num",
      "orgs": [
        {
          "name": "Landlord_num",
          "peers": "peer_num"
        },
        {
          "name": "Tenant_num",
          "peers": "peer_num"
        },
        {
          "name": "Guest_num",
          "peers": "peer_num"
        },
        {
          "name": "Sensors_num",
          "peers": "peer_num"
        }
      ]
    },
  "chaincodes":
    {
      "name": "chaincode_name",
      "channel": "home_num",
      "endorsement": "OR(all MSP orgs)"
    }
}
@endjson