################################################################################
#   SECTION: Capabilities
################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

################################################################################
#   CHANNEL Defaults
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#   Section: Organizations
################################################################################
Organizations:
    - &Orderer
      Name: OrdererMSP
      ID: OrdererMSP
      MSPDir: crypto-config/peerOrganizations/orderer.project.it/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('OrdererMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"

      AnchorPeers:

    - &Landlord1
      Name: Landlord1MSP
      ID: Landlord1MSP
      MSPDir: crypto-config/peerOrganizations/landlord1.project.it/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('Landlord1MSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('Landlord1MSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('Landlord1MSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('Landlord1MSP.member')"

      AnchorPeers:
          - Host: peer0.landlord1.project.it
            Port: 7041

    - &Tenant1
      Name: Tenant1MSP
      ID: Tenant1MSP
      MSPDir: crypto-config/peerOrganizations/tenant1.project.it/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('Tenant1MSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('Tenant1MSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('Tenant1MSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('Tenant1MSP.member')"

      AnchorPeers:
          - Host: peer0.tenant1.project.it
            Port: 7061

    - &Guest1
      Name: Guest1MSP
      ID: Guest1MSP
      MSPDir: crypto-config/peerOrganizations/guest1.project.it/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('Guest1MSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('Guest1MSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('Guest1MSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('Guest1MSP.member')"

      AnchorPeers:
          - Host: peer0.guest1.project.it
            Port: 7081

################################################################################
#   SECTION: Application
################################################################################
Application: &ApplicationDefaults
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

################################################################################
#   SECTION: Orderer
################################################################################
Orderer: &Group1Defaults
    OrdererType: etcdraft
    Addresses:
        - orderer0.group1.orderer.project.it:7030
        - orderer1.group1.orderer.project.it:7031
    EtcdRaft:
        Consenters:
            - Host: orderer0.group1.orderer.project.it
              Port: 7030
              ClientTLSCert: crypto-config/peerOrganizations/orderer.project.it/peers/orderer0.group1.orderer.project.it/tls/server.crt
              ServerTLSCert: crypto-config/peerOrganizations/orderer.project.it/peers/orderer0.group1.orderer.project.it/tls/server.crt

            - Host: orderer1.group1.orderer.project.it
              Port: 7031
              ClientTLSCert: crypto-config/peerOrganizations/orderer.project.it/peers/orderer1.group1.orderer.project.it/tls/server.crt
              ServerTLSCert: crypto-config/peerOrganizations/orderer.project.it/peers/orderer1.group1.orderer.project.it/tls/server.crt

    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Orderer policies, their canonical path is
    #   /Channel/Orderer/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities

################################################################################
#   Profile
################################################################################
# https://github:com/hyperledger/fabric/blob/master/sampleconfig/configtx.yaml

Profiles:
    # Profile used to create Genesis block for group group1 #
    Group1Genesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *Group1Defaults
            Organizations:
                - *Orderer
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Orderer
                    - *Landlord1
                    - *Tenant1
                    - *Guest1

    # Profile used to create channeltx for home1 #
    Home1:
        <<: *ChannelDefaults
        Orderer:
            <<: *Group1Defaults
            Organizations:
                - *Orderer
            Capabilities:
                <<: *ApplicationCapabilities
        Consortium: SampleConsortium
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Landlord1
                    - *Tenant1
                    - *Guest1
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Landlord1
                - *Tenant1
                - *Guest1
