PeerOrgs:
  - Name: Orderer
    Domain: orderer.project.it
    Specs:
      - Hostname: orderer0.group1
      - Hostname: orderer1.group1
      - Hostname: orderer2.group1
    Template:
      Count: 0
    Users:
      Count: 1
