global:
  scrape_interval: 1s
  external_labels:
    monitor: 'devopsage-monitor'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: [ "localhost:9090" ]
  - job_name: "orderers"
    scrape_interval: 5s
    static_configs:
      - targets: [ "localhost:8030" ]
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: [ 'cadvisor:8080' ]
  - job_name: node
    static_configs:
      - targets: [ 'node-exporter:9100' ]